name: Jakob Törmä Ruhl
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

permalink: /blog/:year/:month/:day/:title

twitter_username:     lerusius
github_username:      litasa
linkedin_username:    jakob-torma-ruhl
email: jakob.ruhl@gmail.com

#Gems
gems: [jekyll-paginate, jekyll-sitemap, jekyll-feed]
paginate: 5
paginate_path: "/page:num/"

sort_tag: '/blog/sort_tag'
sort_date: '/blog/sort_date'

images: '{{site.baseurl}}/images/'

reCaptcha: 
  siteKey: '6LcqJhwUAAAAAIXLYRibDgFsVhI4c_B9f5c7-_wg'

# Staticman comments (full configuration in staticman.yml)
staticman:
  branch                 : "master"
