name: Jakob Törmä Ruhl
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

#Gems
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/page:num/"

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'http://codinfox.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'
