name: Jakob Törmä Ruhl
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

twitter_username:     Litasa
github_username:      litasa
linkedin_username:    jakob-torma-ruhl
email: jakob.ruhl@gmail.com

#Gems
gems: [jekyll-paginate, jekyll-sitemap, jekyll-feed]
paginate: 5
paginate_path: "/page:num/"

sort_tag: '/blog/sort_tag'
sort_date: '/blog/sort_date'

# Staticman comments (full configuration in staticman.yml)
staticman:
  branch                 : "master"